#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CalculatorAndroid.Resource", IsApplication=true)]

namespace CalculatorAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010004
			public const int alignmentMode = 2130771972;
			
			// aapt resource value: 0x7f010002
			public const int columnCount = 2130771970;
			
			// aapt resource value: 0x7f010006
			public const int columnOrderPreserved = 2130771974;
			
			// aapt resource value: 0x7f010015
			public const int font = 2130771989;
			
			// aapt resource value: 0x7f01000e
			public const int fontProviderAuthority = 2130771982;
			
			// aapt resource value: 0x7f010011
			public const int fontProviderCerts = 2130771985;
			
			// aapt resource value: 0x7f010012
			public const int fontProviderFetchStrategy = 2130771986;
			
			// aapt resource value: 0x7f010013
			public const int fontProviderFetchTimeout = 2130771987;
			
			// aapt resource value: 0x7f01000f
			public const int fontProviderPackage = 2130771983;
			
			// aapt resource value: 0x7f010010
			public const int fontProviderQuery = 2130771984;
			
			// aapt resource value: 0x7f010014
			public const int fontStyle = 2130771988;
			
			// aapt resource value: 0x7f010016
			public const int fontWeight = 2130771990;
			
			// aapt resource value: 0x7f01000a
			public const int layout_column = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int layout_columnSpan = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int layout_columnWeight = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int layout_gravity = 2130771981;
			
			// aapt resource value: 0x7f010007
			public const int layout_row = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int layout_rowSpan = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int layout_rowWeight = 2130771977;
			
			// aapt resource value: 0x7f010000
			public const int orientation = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int rowCount = 2130771969;
			
			// aapt resource value: 0x7f010005
			public const int rowOrderPreserved = 2130771973;
			
			// aapt resource value: 0x7f010003
			public const int useDefaultMargins = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f060000
			public const int abc_action_bar_embed_tabs = 2131099648;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070000
			public const int notification_action_color_filter = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int notification_icon_bg_color = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int ripple_material_light = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int secondary_text_default_material_light = 2131165187;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040005
			public const int compat_button_inset_horizontal_material = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int compat_button_inset_vertical_material = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int compat_button_padding_horizontal_material = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int compat_button_padding_vertical_material = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int compat_control_corner_material = 2130968585;
			
			// aapt resource value: 0x7f040000
			public const int default_gap = 2130968576;
			
			// aapt resource value: 0x7f04000a
			public const int notification_action_icon_size = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int notification_action_text_size = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int notification_big_circle_margin = 2130968588;
			
			// aapt resource value: 0x7f040002
			public const int notification_content_margin_start = 2130968578;
			
			// aapt resource value: 0x7f04000d
			public const int notification_large_icon_height = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int notification_large_icon_width = 2130968590;
			
			// aapt resource value: 0x7f040003
			public const int notification_main_column_padding_top = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int notification_media_narrow_margin = 2130968580;
			
			// aapt resource value: 0x7f04000f
			public const int notification_right_icon_size = 2130968591;
			
			// aapt resource value: 0x7f040001
			public const int notification_right_side_padding_top = 2130968577;
			
			// aapt resource value: 0x7f040010
			public const int notification_small_icon_background_padding = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int notification_small_icon_size_as_large = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int notification_subtext_size = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int notification_top_pad = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int notification_top_pad_large_text = 2130968596;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int notification_action_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int notification_bg = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int notification_bg_low = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int notification_bg_low_normal = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int notification_bg_low_pressed = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int notification_bg_normal = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int notification_bg_normal_pressed = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int notification_icon_background = 2130837511;
			
			// aapt resource value: 0x7f02000a
			public const int notification_template_icon_bg = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int notification_template_icon_low_bg = 2130837515;
			
			// aapt resource value: 0x7f020008
			public const int notification_tile_bg = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int notify_panel_notification_icon_bg = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09001e
			public const int action_container = 2131296286;
			
			// aapt resource value: 0x7f09002a
			public const int action_divider = 2131296298;
			
			// aapt resource value: 0x7f09001f
			public const int action_image = 2131296287;
			
			// aapt resource value: 0x7f090020
			public const int action_text = 2131296288;
			
			// aapt resource value: 0x7f09002b
			public const int actions = 2131296299;
			
			// aapt resource value: 0x7f090007
			public const int alignBounds = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int alignMargins = 2131296264;
			
			// aapt resource value: 0x7f090017
			public const int async = 2131296279;
			
			// aapt resource value: 0x7f090018
			public const int blocking = 2131296280;
			
			// aapt resource value: 0x7f090009
			public const int bottom = 2131296265;
			
			// aapt resource value: 0x7f09001c
			public const int calculator_text_view = 2131296284;
			
			// aapt resource value: 0x7f09000a
			public const int center = 2131296266;
			
			// aapt resource value: 0x7f09000b
			public const int center_horizontal = 2131296267;
			
			// aapt resource value: 0x7f09000c
			public const int center_vertical = 2131296268;
			
			// aapt resource value: 0x7f090029
			public const int chronometer = 2131296297;
			
			// aapt resource value: 0x7f09000d
			public const int clip_horizontal = 2131296269;
			
			// aapt resource value: 0x7f09000e
			public const int clip_vertical = 2131296270;
			
			// aapt resource value: 0x7f09000f
			public const int end = 2131296271;
			
			// aapt resource value: 0x7f090010
			public const int fill = 2131296272;
			
			// aapt resource value: 0x7f090011
			public const int fill_horizontal = 2131296273;
			
			// aapt resource value: 0x7f090012
			public const int fill_vertical = 2131296274;
			
			// aapt resource value: 0x7f090019
			public const int forever = 2131296281;
			
			// aapt resource value: 0x7f09001d
			public const int gridLayout1 = 2131296285;
			
			// aapt resource value: 0x7f090005
			public const int horizontal = 2131296261;
			
			// aapt resource value: 0x7f090022
			public const int icon = 2131296290;
			
			// aapt resource value: 0x7f09002c
			public const int icon_group = 2131296300;
			
			// aapt resource value: 0x7f090025
			public const int info = 2131296293;
			
			// aapt resource value: 0x7f09001a
			public const int italic = 2131296282;
			
			// aapt resource value: 0x7f090013
			public const int left = 2131296275;
			
			// aapt resource value: 0x7f090000
			public const int line1 = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int line3 = 2131296257;
			
			// aapt resource value: 0x7f09001b
			public const int normal = 2131296283;
			
			// aapt resource value: 0x7f090027
			public const int notification_background = 2131296295;
			
			// aapt resource value: 0x7f090023
			public const int notification_main_column = 2131296291;
			
			// aapt resource value: 0x7f090021
			public const int notification_main_column_container = 2131296289;
			
			// aapt resource value: 0x7f090014
			public const int right = 2131296276;
			
			// aapt resource value: 0x7f090026
			public const int right_icon = 2131296294;
			
			// aapt resource value: 0x7f090024
			public const int right_side = 2131296292;
			
			// aapt resource value: 0x7f090015
			public const int start = 2131296277;
			
			// aapt resource value: 0x7f090002
			public const int text = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int text2 = 2131296259;
			
			// aapt resource value: 0x7f090028
			public const int time = 2131296296;
			
			// aapt resource value: 0x7f090004
			public const int title = 2131296260;
			
			// aapt resource value: 0x7f090016
			public const int top = 2131296278;
			
			// aapt resource value: 0x7f090006
			public const int vertical = 2131296262;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f0a0000
			public const int status_bar_notification_info_maxnum = 2131361792;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int notification_action = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int notification_action_tombstone = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int notification_template_custom_big = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int notification_template_icon_group = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int notification_template_part_chronometer = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int notification_template_part_time = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int status_bar_notification_info_overflow = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int TextAppearance_Compat_Notification = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int TextAppearance_Compat_Notification_Info = 2131230721;
			
			// aapt resource value: 0x7f080006
			public const int TextAppearance_Compat_Notification_Line2 = 2131230726;
			
			// aapt resource value: 0x7f080002
			public const int TextAppearance_Compat_Notification_Time = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int TextAppearance_Compat_Notification_Title = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int Widget_Compat_NotificationActionContainer = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int Widget_Compat_NotificationActionText = 2131230725;
			
			// aapt resource value: 0x7f080007
			public const int button_calculator = 2131230727;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FontFamily = new int[] {
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987};
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					2130771988,
					2130771989,
					2130771990};
			
			// aapt resource value: 1
			public const int FontFamilyFont_font = 1;
			
			// aapt resource value: 0
			public const int FontFamilyFont_fontStyle = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_fontWeight = 2;
			
			public static int[] GridLayout = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974};
			
			// aapt resource value: 4
			public const int GridLayout_alignmentMode = 4;
			
			// aapt resource value: 2
			public const int GridLayout_columnCount = 2;
			
			// aapt resource value: 6
			public const int GridLayout_columnOrderPreserved = 6;
			
			// aapt resource value: 0
			public const int GridLayout_orientation = 0;
			
			// aapt resource value: 1
			public const int GridLayout_rowCount = 1;
			
			// aapt resource value: 5
			public const int GridLayout_rowOrderPreserved = 5;
			
			// aapt resource value: 3
			public const int GridLayout_useDefaultMargins = 3;
			
			public static int[] GridLayout_Layout = new int[] {
					16842996,
					16842997,
					16842998,
					16842999,
					16843000,
					16843001,
					16843002,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981};
			
			// aapt resource value: 1
			public const int GridLayout_Layout_android_layout_height = 1;
			
			// aapt resource value: 2
			public const int GridLayout_Layout_android_layout_margin = 2;
			
			// aapt resource value: 6
			public const int GridLayout_Layout_android_layout_marginBottom = 6;
			
			// aapt resource value: 3
			public const int GridLayout_Layout_android_layout_marginLeft = 3;
			
			// aapt resource value: 5
			public const int GridLayout_Layout_android_layout_marginRight = 5;
			
			// aapt resource value: 4
			public const int GridLayout_Layout_android_layout_marginTop = 4;
			
			// aapt resource value: 0
			public const int GridLayout_Layout_android_layout_width = 0;
			
			// aapt resource value: 10
			public const int GridLayout_Layout_layout_column = 10;
			
			// aapt resource value: 11
			public const int GridLayout_Layout_layout_columnSpan = 11;
			
			// aapt resource value: 12
			public const int GridLayout_Layout_layout_columnWeight = 12;
			
			// aapt resource value: 13
			public const int GridLayout_Layout_layout_gravity = 13;
			
			// aapt resource value: 7
			public const int GridLayout_Layout_layout_row = 7;
			
			// aapt resource value: 8
			public const int GridLayout_Layout_layout_rowSpan = 8;
			
			// aapt resource value: 9
			public const int GridLayout_Layout_layout_rowWeight = 9;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
