#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RegisterAdd.Resource", IsApplication=true)]

namespace RegisterAdd
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int accentColor = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int ic_launcher_background = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int primaryColor = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int primaryDarkColor = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int primaryLightColor = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int primaryTextColor = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int secondaryColor = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int secondaryDarkColor = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int secondaryLightColor = 2130771976;
			
			// aapt resource value: 0x7F010009
			public const int secondaryTextColor = 2130771977;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F020000
			public const int activity_horizontal_margin = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int activity_vertical_margin = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int fab_margin = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int nav_header_height = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int nav_header_vertical_spacing = 2130837508;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F030000
			public const int alert_circle = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int alert_circle_outline = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int charter = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int ic_menu_camera = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int ic_menu_gallery = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int ic_menu_manage = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int ic_menu_send = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int ic_menu_share = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int ic_menu_slideshow = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int side_nav_bar = 2130903049;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F040000
			public const int action_settings = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int base_view = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int base_view1 = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int base_view2 = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int base_view3 = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int base_view4 = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int buttonRegisterReg = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int coordinatorLayoutMain = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int drawer_layout = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int editTextFirstnameReg = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int editTextLastnameReg = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int editTextPasswordReg = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int editTextPasswordRegRepeat = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public const int editTextUsernameReg = 2130968589;
			
			// aapt resource value: 0x7F04000E
			public const int flContent = 2130968590;
			
			// aapt resource value: 0x7F04000F
			public const int imageView = 2130968591;
			
			// aapt resource value: 0x7F040010
			public const int imgLogo = 2130968592;
			
			// aapt resource value: 0x7F040011
			public const int nav_camera = 2130968593;
			
			// aapt resource value: 0x7F040012
			public const int nav_gallery = 2130968594;
			
			// aapt resource value: 0x7F040013
			public const int nav_view = 2130968595;
			
			// aapt resource value: 0x7F040014
			public const int recyclerViewUsers = 2130968596;
			
			// aapt resource value: 0x7F040015
			public const int textView = 2130968597;
			
			// aapt resource value: 0x7F040016
			public const int textviewConfirmPassword = 2130968598;
			
			// aapt resource value: 0x7F040017
			public const int textviewFirstname = 2130968599;
			
			// aapt resource value: 0x7F040018
			public const int textviewLabel = 2130968600;
			
			// aapt resource value: 0x7F040019
			public const int textviewLastname = 2130968601;
			
			// aapt resource value: 0x7F04001A
			public const int textviewPassword = 2130968602;
			
			// aapt resource value: 0x7F04001B
			public const int textviewSince = 2130968603;
			
			// aapt resource value: 0x7F04001C
			public const int textviewText = 2130968604;
			
			// aapt resource value: 0x7F04001D
			public const int textviewUsername = 2130968605;
			
			// aapt resource value: 0x7F04001E
			public const int textviewUsers = 2130968606;
			
			// aapt resource value: 0x7F04001F
			public const int toolbar = 2130968607;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F050000
			public const int activity_main = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int activity_splash = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int add_user_fragment = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int app_bar_main = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int base_view = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int nav_header_main = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int user_info = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int user_item_text_view = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int view_users_fragment = 2131034120;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F060000
			public const int activity_main_drawer = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int menu_main = 2131099649;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F070000
			public const int app_icon = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int baseline_add_24 = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int baseline_add_black_24 = 2131165186;
			
			// aapt resource value: 0x7F070003
			public const int ic_launcher = 2131165187;
			
			// aapt resource value: 0x7F070004
			public const int ic_launcher_foreground = 2131165188;
			
			// aapt resource value: 0x7F070005
			public const int ic_launcher_round = 2131165189;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F080000
			public const int action_settings = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int add = 2131230721;
			
			// aapt resource value: 0x7F080002
			public const int app_name = 2131230722;
			
			// aapt resource value: 0x7F080003
			public const int navigation_drawer_close = 2131230723;
			
			// aapt resource value: 0x7F080004
			public const int navigation_drawer_open = 2131230724;
			
			// aapt resource value: 0x7F080005
			public const int users = 2131230725;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F090000
			public const int AppTheme = 2131296256;
			
			// aapt resource value: 0x7F090001
			public const int AppTheme_AppBarOverlay = 2131296257;
			
			// aapt resource value: 0x7F090002
			public const int AppTheme_NoActionBar = 2131296258;
			
			// aapt resource value: 0x7F090003
			public const int AppTheme_PopupOverlay = 2131296259;
			
			// aapt resource value: 0x7F090004
			public const int splashscreen = 2131296260;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
